name: KMP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - numpy>=1.24.0
  - pillow>=10.0.0
  - pip
  - pip:
    - torch-geometric>=2.4.0
    - torch-scatter>=2.1.2
    - torch-sparse>=0.6.18
    - torch-cluster>=1.6.3
    - torch-spline-conv>=1.2.2
    - matplotlib>=3.8.0
    - opencv-python>=4.8.0
    - tqdm>=4.66.0
    - yacs>=0.1.8
    - pandas>=2.1.0
    - networkx>=3.2.0
    - scipy>=1.11.0
    - scikit-learn>=1.3.0
    - h5py>=3.10.0
